name: tag
on:
  push:
    tags:
    - 'v*'

jobs:
  start:
    # uses: actions/checkout@v3
    uses: ./.github/workflows/v1.yml

# on:
#   workflow_dispatch:
#     branches: [main]

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# on:
#   schedule:
#     - cron: '30 1 * * *'
